#object that store enviroments variables that could be have sensitive data like a password
apiVersion: v1
kind: Secret
metadata:
  name: account-secret
  labels:
    app: account-sqldata
    #meant that we can use arbitrary key pair values
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cEBzc3cwcmQ=
  MYSQL_DATABASE: YWNjb3VudF9kYg==