kind: Service
apiVersion: v1
metadata:
  name: account-sqldata-service
  labels:
    app: account-sqldata
spec: 
  clusterIP: 10.96.1.3 
  ipFamilies:
  - IPv4
  ports:
  - protocol: TCP
    name: mysql
    port: 3306
    nodePort : 31432 
  #type: LoadBalancer
  type: NodePort
  selector:
   app: account-sqldata