apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
  labels:
    app: account-service
spec:
  selector:
   matchLabels:
    app: account-service
  replicas: 2
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service-container
          image: pm44019/mcs_account-service:v1.0.3
          env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://account-sqldata-service:3306/account_db"
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: "http://eureka-server-service/eureka/"
          - name: SPRING_RABBITMQ_HOST
            value: "rabbitmq-service-service"
          - name: SPRING_RABBITMQ_USERNAME
            value: "guest"
          - name: SPRING_RABBITMQ_PASSWORD
            value: "guest"
          ports:
            - containerPort: 8001
              name: http