apiVersion: v1
kind: Service
metadata:
  name: account-service-service
  labels:
    app: account-service
spec:
  type: LoadBalancer
  selector:
    app: account-service
  ports:
    - protocol: TCP
      port: 81
      targetPort: http