apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  labels:
    app: user-service
spec:
  type: LoadBalancer
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 81
      targetPort: http